'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {Library,validatePack,verifyEnvelope,sha,safeRelative,atomicJson}=require('../src/atlas/library.cjs');
const {bootstrap}=require('../src/atlas/bootstrap.cjs');
const {sign}=require('../scripts/atlas/publish-packs.cjs');
const {ApplicationUpdate}=require('../src/atlas/application-update.cjs');
const fixtureBase=path.resolve(__dirname,'../build-check/fixtures');fs.mkdirSync(fixtureBase,{recursive:true});
const onlineSource='https://github.com/lordfelixmotosr/atlas/releases/latest/download/';
function cleanup(root){assert(root.startsWith(fixtureBase+path.sep));fs.rmSync(root,{recursive:true,force:true});}
function fixture(t){const root=fs.mkdtempSync(path.join(fixtureBase,'atlas-test-')),resources=path.join(root,'resources'),keys=crypto.generateKeyPairSync('ed25519');fs.mkdirSync(resources);const trust={keys:{'atlas-local-1':keys.publicKey.export({format:'pem',type:'spki'})}};fs.writeFileSync(path.join(resources,'trust.json'),JSON.stringify(trust));t.after(()=>cleanup(root));return{root,resources,keys,trust};}
function pack(version='0.1.0',extra={}){const text='---\nname: test-pack\ndescription: Test references\n---\n\nHarmony example for apparel.';return{type:'pack',id:'test-pack',name:'Example pack',description:'Test references',category:'skills',source:'https://example.com/references',license:'MIT',version,minAtlasVersion:'0.1.0',gameVersions:['1.6'],issuedAt:Date.now()-1000,expiresAt:Date.now()+86400000,files:[{path:'skills/test-pack/SKILL.md',encoding:'utf8',content:text,sha256:sha(Buffer.from(text))}],...extra};}
function feed(f,packs,sequence=1,application){const folder=path.join(f.root,'updates');fs.mkdirSync(folder,{recursive:true});const entries=packs.map(pack=>{const file=pack.id+'-'+pack.version+'.atlas.json',bytes=sign(pack,f.keys.privateKey);fs.writeFileSync(path.join(folder,file),bytes);return{id:pack.id,version:pack.version,file,sha256:sha(bytes)};});fs.writeFileSync(path.join(folder,'index.atlas.json'),sign({type:'feed',sequence,issuedAt:Date.now()-1000,expiresAt:Date.now()+86400000,packs:entries,application},f.keys.privateKey));}
test('online distribution migrates the bundled default once while preserving custom and offline choices',t=>{
 const f=fixture(t);fs.writeFileSync(path.join(f.resources,'distribution.json'),JSON.stringify({updateSource:onlineSource,feedRevision:1}));
 const library=new Library(f.root,f.resources);assert.equal(library.config.source,onlineSource);library.configure({source:'updates',autoUpdate:false});assert.equal(new Library(f.root,f.resources).config.source,'updates');assert.equal(new Library(f.root,f.resources).config.autoUpdate,false);
 library.configure({source:'https://example.com/custom'});assert.equal(new Library(f.root,f.resources).config.source,'https://example.com/custom');
 fs.writeFileSync(library.configPath,JSON.stringify({source:'updates',autoUpdate:true}));assert.equal(new Library(f.root,f.resources).config.source,onlineSource);
});
test('GitHub release redirects are restricted to the repository and asset host with credentials omitted',async t=>{
 const f=fixture(t),calls=[];const responses=[new Response(null,{status:302,headers:{location:'https://github.com/lordfelixmotosr/atlas/releases/download/v0.2.2/index.atlas.json'}}),new Response(null,{status:302,headers:{location:'https://release-assets.githubusercontent.com/github-production-release-asset/123/abc?sig=temporary'}}),new Response('signed feed')];
 const library=new Library(f.root,f.resources,{fetch:async(url,options)=>{calls.push({url:String(url),options});return responses.shift()}});
 assert.equal((await library.obtain(onlineSource,'index.atlas.json')).toString(),'signed feed');assert.equal(calls.length,3);assert(calls.every(call=>call.options.credentials==='omit'&&call.options.redirect==='manual'&&!call.options.headers));
});
test('unsafe release redirects, loops and oversized downloads are rejected',async t=>{
 const f=fixture(t),library=new Library(f.root,f.resources);
 for(const destination of ['http://github.com/lordfelixmotosr/atlas/releases/download/v1/index.atlas.json','https://github.com/other/repo/releases/download/v1/index.atlas.json','https://evil.example/file','https://user:secret@release-assets.githubusercontent.com/github-production-release-asset/1/a','https://release-assets.githubusercontent.com/other/path']){
  library.fetch=async()=>new Response(null,{status:302,headers:{location:destination}});await assert.rejects(library.obtain(onlineSource,'index.atlas.json'),/trusted release/);
 }
 library.fetch=async()=>new Response(null,{status:302,headers:{location:onlineSource+'index.atlas.json'}});await assert.rejects(library.obtain(onlineSource,'index.atlas.json'),/Too many/);
 library.fetch=async()=>new Response('oversized');await assert.rejects(library.obtain(onlineSource,'index.atlas.json',2),/size limit/);
});
test('custom HTTPS feeds keep automatic redirects disabled',async t=>{
 const f=fixture(t);let options;const library=new Library(f.root,f.resources,{fetch:async(_url,value)=>{options=value;throw new Error('redirect disabled')}});
 await assert.rejects(library.obtain('https://example.com/feed','index.atlas.json'),/redirect disabled/);assert.equal(options.redirect,'error');
});
test('portable bootstrap assigns paths before profile readers and survives a moved folder',t=>{const f=fixture(t),calls=[];const app={setName:v=>calls.push(['name',v]),setPath:(k,v)=>calls.push([k,v]),setAppLogsPath:v=>calls.push(['logs',v])};bootstrap(app,f.root);assert.deepEqual(calls[0],['name','Atlas']);assert.equal(calls.find(([k])=>k==='userData')[1],path.join(f.root,'data/profile'));const moved=path.join(f.root,'Moved Atlas with spaces');bootstrap(app,moved);assert.equal(process.env.ATLAS_ROOT,moved);assert(calls.every(([,v])=>v==='Atlas'||!v.includes('AppData')));});
test('approved packs install, defer during active work, search, override and roll back',async t=>{const f=fixture(t);let busy=false;feed(f,[pack()]);const library=new Library(f.root,f.resources,{busy:()=>busy});await library.update();assert.equal(library.status().packs[0].version,'0.1.0');assert.equal(library.search('Harmony apparel').length,1);assert.equal(library.skillRoots().length,1);const custom={name:'test-pack',filePath:'custom'};assert.equal(library.mergeSkills([{name:'test-pack',filePath:'managed'}],[custom])[0],custom);
 fs.mkdirSync(path.join(f.root,'custom/skills'),{recursive:true});fs.writeFileSync(path.join(f.root,'custom/skills/personal.txt'),'keep');busy=true;feed(f,[pack('0.2.0')],2);await library.update();assert.equal(library.state.active['test-pack'],'0.1.0');assert.equal(library.state.pending['test-pack'],'0.2.0');assert.throws(()=>library.revert('test-pack'),/active/);busy=false;assert(library.activatePending());assert.equal(library.state.active['test-pack'],'0.2.0');library.revert('test-pack');assert.equal(library.state.active['test-pack'],'0.1.0');assert.equal(fs.readFileSync(path.join(f.root,'custom/skills/personal.txt'),'utf8'),'keep');
 const restart=new Library(f.root,f.resources);assert.equal(restart.state.active['test-pack'],'0.1.0');assert.equal(restart.search('apparel').length,1);
});
test('tampered, expired, untrusted, replayed and incompatible releases preserve working library',async t=>{const f=fixture(t);feed(f,[pack()],10);const library=new Library(f.root,f.resources);await library.update();const indexPath=path.join(f.root,'updates/index.atlas.json'),envelope=JSON.parse(fs.readFileSync(indexPath));envelope.signature=Buffer.alloc(64).toString('base64');fs.writeFileSync(indexPath,JSON.stringify(envelope));await assert.rejects(()=>library.update(),/signature/);assert.equal(library.state.active['test-pack'],'0.1.0');feed(f,[pack('0.2.0')],9);await assert.rejects(()=>library.check(),/outdated/);feed(f,[pack('0.2.0',{minAtlasVersion:'9.0.0'})],11);await assert.rejects(()=>library.update(),/incompatible/);
 feed(f,[pack('0.2.0',{gameVersions:['1.7']})],12);await assert.rejects(()=>library.update(),/incompatible/);
 const expired=pack('0.2.0',{expiresAt:Date.now()-500});assert.throws(()=>verifyEnvelope(sign(expired,f.keys.privateKey),f.trust),/expired/);assert.throws(()=>verifyEnvelope(sign(pack(),f.keys.privateKey,'stranger'),f.trust),/trusted/);assert.equal(library.search('Harmony').length,1);
});
test('invalid paths, file checksums, duplicate paths, executable packs and links are rejected',t=>{const f=fixture(t);for(const input of ['../outside','/absolute','C:/secret','foo\\bar','a/../b','CON.txt','foo/aux','a/evil:stream','a/file.','a//b'])assert.throws(()=>safeRelative(input));assert.throws(()=>validatePack(pack('0.1.0',{files:[{path:'install.exe',encoding:'utf8',content:'x',sha256:sha(Buffer.from('x'))}]})),/Invalid reference/);const corrupt=pack();corrupt.files[0].sha256='0'.repeat(64);assert.throws(()=>validatePack(corrupt),/integrity/);const duplicate=pack();duplicate.files.push({...duplicate.files[0],path:duplicate.files[0].path.toUpperCase()});assert.throws(()=>validatePack(duplicate),/Invalid reference/);
 const outside=fs.mkdtempSync(path.join(fixtureBase,'atlas-outside-'));t.after(()=>cleanup(outside));fs.mkdirSync(path.join(f.root,'library'));fs.symlinkSync(outside,path.join(f.root,'library/packs'),'junction');const library=new Library(f.root,f.resources);const linked=pack();assert.throws(()=>library.install(linked,sign(linked,f.keys.privateKey)),/link|escaped/);assert.equal(fs.readdirSync(outside).length,0);
});
test('network failures, changed installed files and concurrent checks do not lose prior context',async t=>{const f=fixture(t);feed(f,[pack()]);const library=new Library(f.root,f.resources);await library.update();library.configure({source:'https://example.com/atlas'});library.fetch=async()=>{throw new Error('offline');};await assert.rejects(()=>library.update(),/offline/);assert.equal(library.state.active['test-pack'],'0.1.0');assert.equal(library.search('Harmony').length,1);
 const target=library.file('test-pack','skills/test-pack/SKILL.md');fs.appendFileSync(target,'tampered');assert.throws(()=>library.verifyInstalled('test-pack','0.1.0'),/integrity/);assert.throws(()=>library.configure({source:'https://secret:pass@example.com/a'}),/clean HTTPS/);
 let release;library.fetch=()=>new Promise(resolve=>{release=resolve;});const check=library.check();await new Promise(resolve=>setImmediate(resolve));await assert.rejects(()=>library.check(),/Another/);release({ok:false,status:503});await assert.rejects(()=>check,/503/);
});
test('application updates use the trusted feed and checksum, and respect active work',async t=>{const f=fixture(t),bytes=Buffer.from('dummy update package');feed(f,[],1,{version:'0.3.0',file:'Atlas-0.2.0.zip',size:bytes.length,sha256:sha(bytes)});fs.writeFileSync(path.join(f.root,'updates/Atlas-0.2.0.zip'),bytes);let busy=true;const library=new Library(f.root,f.resources),app=new ApplicationUpdate(library,{app:{}},()=>busy);await app.download();assert.equal(app.status().ready,'0.3.0');assert.throws(()=>app.install(),/active work/);busy=false;fs.appendFileSync(app.ready.path,'tampered');assert.throws(()=>app.install(),/changed/);feed(f,[],2,{version:'0.4.0',file:'Atlas-0.2.0.zip',size:bytes.length,sha256:'0'.repeat(64)});await assert.rejects(()=>app.download(),/checksum/);});

test('cached references remain signed after restart, and changed files cannot become agent skills',async t=>{
 const f=fixture(t);feed(f,[pack()]);const library=new Library(f.root,f.resources);await library.update();
 const dir=library.packDir('test-pack','0.1.0');const manifest=JSON.parse(fs.readFileSync(path.join(dir,'pack.json')));
 fs.appendFileSync(path.join(dir,'skills/test-pack/SKILL.md'),'forged instructions');manifest.files[0].sha256=sha(fs.readFileSync(path.join(dir,'skills/test-pack/SKILL.md')));fs.writeFileSync(path.join(dir,'pack.json'),JSON.stringify(manifest));
 const restart=new Library(f.root,f.resources);assert.throws(()=>restart.search('Harmony'),/integrity/);assert.deepEqual(restart.skillRoots(),[]);
 const envelope=JSON.parse(fs.readFileSync(path.join(dir,'release.atlas.json')));envelope.signature=Buffer.alloc(64).toString('base64');fs.writeFileSync(path.join(dir,'release.atlas.json'),JSON.stringify(envelope));assert.throws(()=>restart.verifyInstalled('test-pack','0.1.0'),/signature/);
});

test('portable bundled shell settings rebase when the app folder moves',t=>{const f=fixture(t),app={setName(){},setPath(){},setAppLogsPath(){}};const shell=path.join(f.root,'tools/git/bin/bash.exe');fs.mkdirSync(path.dirname(shell),{recursive:true});fs.writeFileSync(shell,'fake test shell');bootstrap(app,f.root);const original=JSON.parse(fs.readFileSync(path.join(f.root,'data/profile/pi-agent/settings.json')));assert.equal(original.shellPath,shell);const moved=path.join(f.root,'Moved');fs.mkdirSync(path.join(moved,'tools/git/bin'),{recursive:true});fs.copyFileSync(shell,path.join(moved,'tools/git/bin/bash.exe'));fs.mkdirSync(path.join(moved,'data/profile/pi-agent'),{recursive:true});fs.writeFileSync(path.join(moved,'data/profile/pi-agent/settings.json'),JSON.stringify({...original,thinkingLevel:'xhigh'}));bootstrap(app,moved);const next=JSON.parse(fs.readFileSync(path.join(moved,'data/profile/pi-agent/settings.json')));assert.equal(next.shellPath,path.join(moved,'tools/git/bin/bash.exe'));assert.equal(next.thinkingLevel,'xhigh');assert.equal(process.env.GIT_CONFIG_GLOBAL,path.join(moved,'data/git/config'));});

test('reference viewer shows code as escaped text with scripts and external loads disabled',async t=>{const f=fixture(t),file=path.join(f.root,'example.py');fs.writeFileSync(file,'<script>unsafe()</script>');const {referenceHtml,openReference}=require('../src/atlas/reference-view.cjs');const html=referenceHtml(file);assert(html.includes('&lt;script&gt;'));assert(!html.includes('<script>'));assert(html.includes("default-src 'none'"));let options,url;const windows=new Set();class Viewer{constructor(value){options=value;this.webContents={setWindowOpenHandler:fn=>assert.deepEqual(fn(),{action:'deny'})};}once(){}loadURL(value){url=value;return Promise.resolve();}}await openReference(file,{BrowserWindow:Viewer},null,windows);assert.equal(options.webPreferences.javascript,false);assert.equal(options.webPreferences.nodeIntegration,false);assert.equal(options.webPreferences.sandbox,true);assert(url.startsWith('data:text/html'));assert.equal(windows.size,1);});

test('automatic app updates can proceed when new reference packs require a newer Atlas',async t=>{const f=fixture(t);feed(f,[pack()],1);const existing=new Library(f.root,f.resources);await existing.update();existing.configure({source:'updates'});const bytes=Buffer.from('test app release');feed(f,[pack('0.2.0',{minAtlasVersion:'9.0.0'})],2,{version:'0.3.0',file:'release.zip',size:bytes.length,sha256:sha(bytes)});fs.writeFileSync(path.join(f.root,'updates/release.zip'),bytes);let quit;const electron={app:{on:(name,fn)=>{if(name==='before-quit')quit=fn;}},ipcMain:{handle(){}},shell:{},dialog:{}};const runtime=require('../src/atlas/runtime.cjs').init({root:f.root,resources:f.resources,host:{},getWindow:()=>null,electron,isBusy:()=>false});t.after(()=>quit?.());await runtime.ready;for(let i=0;i<50&&!runtime.application.ready;i++)await new Promise(resolve=>setTimeout(resolve,20));assert.equal(runtime.application.status().ready,'0.3.0');assert.equal(runtime.library.state.active['test-pack'],'0.1.0');assert(runtime.library.config.lastError.includes('incompatible'));});
