const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('../build-tools/native/node_modules/typescript');
const source=fs.readFileSync(require('node:path').resolve(__dirname,'../src/agent/agent-host.ts'),'utf8'),parsed=ts.createSourceFile('host.ts',source,ts.ScriptTarget.Latest,true),host=parsed.statements.find(node=>ts.isClassDeclaration(node)&&node.name?.text==='AgentHost'),method=host.members.find(node=>node.name?.getText(parsed)==='describeModChanges');
const code=ts.transpileModule('class DescriptionHost { atlasChangeDescriptionsOpenAI=0; '+method.getText(parsed)+' }; module.exports=DescriptionHost;', {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,moduleFixture={exports:{}};
vm.runInNewContext(code,{module:moduleFixture,AbortController,console});const DescriptionHost=moduleFixture.exports;
function fixture(provider='openai-codex'){const host=new DescriptionHost(),model={provider,id:'fixture-model',name:'Fixture model'};host.resolveModel=()=>model;host.modelRegistry={hasConfiguredAuth:()=>true};return {host,model};}
test('description uses the configured runtime and account without sending or steering chat',async()=>{
 const {host,model}=fixture(),signal=new AbortController().signal;host.modelRuntime={completeSimple:async(selected,context,options)=>{assert.equal(selected,model);assert.equal(host.atlasChangeDescriptionsOpenAI,1);assert.equal(options.signal,signal);assert.equal(options.maxTokens,1600);assert.match(context.systemPrompt,/untrusted evidence/);assert.equal(context.messages[0].content,'{"changes":"fixture"}');return {stopReason:'stop',content:[{type:'text',text:'Added recruitable mercenaries.'}]};}};
 const result=await host.describeModChanges('{"changes":"fixture"}',signal);assert.equal(result.text,'Added recruitable mercenaries.');assert.equal(result.model,'Fixture model');assert.equal(host.atlasChangeDescriptionsOpenAI,0);
});
test('provider errors, cancellation and unavailable auth cannot return a successful description',async()=>{
 for(const mode of ['error','cancelled','missing']){const {host}=fixture(),controller=new AbortController();host.modelRegistry.hasConfiguredAuth=()=>mode!=='missing';host.modelRuntime={completeSimple:async()=>{if(mode==='cancelled'){controller.abort();return {content:[{type:'text',text:'late'}],stopReason:'stop'};}return {stopReason:'error',errorMessage:'Provider declined',content:[]};}};await assert.rejects(host.describeModChanges('{}',controller.signal),mode==='error'?/Provider declined/:mode==='cancelled'?/cancelled/:/Connect an AI account/);assert.equal(host.atlasChangeDescriptionsOpenAI,0);}
});
