'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ts=require('../build-tools/native/node_modules/typescript');
const {Tasks}=require('../src/atlas/tasks.cjs');const files=require('../src/atlas/project-files.cjs');
const base=path.resolve(__dirname,'../build-check/fixtures');fs.mkdirSync(base,{recursive:true});
function normalize(){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/atlas/model-capabilities.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{module,exports:module.exports});return module.exports.atlasModelCapabilities;}
test('known OpenAI models retain verified context across stale catalogue and account metadata without changing unrelated providers',()=>{const fix=normalize();for(const provider of ['openai','openai-codex'])for(const id of ['gpt-6-sol','gpt-6.1-sol','gpt-6-astra','gpt-6.1-sol-2026-09-24']){const model={provider,id,contextWindow:272000,maxTokens:128000,headers:{custom:'retained'}};const corrected=fix(model);assert.equal(corrected.contextWindow,1050000);assert.equal(model.contextWindow,272000);assert.equal(corrected.headers,model.headers);assert.equal(fix({...corrected,contextWindow:272000}).contextWindow,1050000);}for(const model of [{provider:'openai',id:'gpt-5.5',contextWindow:272000},{provider:'custom',id:'gpt-6-sol',contextWindow:100000},{provider:'openai',id:'gpt-6-sol',contextWindow:50000,baseUrl:'https://private.example/api'}])assert.equal(fix(model),model);});
test('actual bundled session usage reads the corrected model limit after compaction and new responses',async()=>{const {AgentSession}=await import(require('node:url').pathToFileURL(path.resolve(__dirname,'../dist/Atlas-0.1.0-release/resources/node_modules/@earendil-works/pi-coding-agent/dist/core/agent-session.js')).href);const model=normalize()({provider:'openai-codex',id:'gpt-6.1-sol',contextWindow:272000});const usage=AgentSession.prototype.getContextUsage.call({model,messages:[],sessionManager:{getBranch:()=>[]}});assert.equal(usage.contextWindow,1050000);assert.equal(usage.percent,0);const compacted=AgentSession.prototype.getContextUsage.call({model,messages:[],sessionManager:{getBranch:()=>[{type:'compaction',summary:'Retained task summary'}]}});assert.equal(compacted.contextWindow,1050000);assert.equal(compacted.tokens,null);const response=AgentSession.prototype.getContextUsage.call({model,messages:[{role:'assistant',usage:{input:200000,output:1000,cacheRead:0,cacheWrite:0,totalTokens:201000},content:[],stopReason:'stop'}],sessionManager:{getBranch:()=>[]}});assert.equal(response.contextWindow,1050000);assert(response.tokens>=200000);});
test('content search returns precise lines, respects case, caps results, skips private folders and supports cancellation',async t=>{const root=fs.mkdtempSync(path.join(base,'search-'));t.after(()=>{assert(root.startsWith(base+path.sep));fs.rmSync(root,{recursive:true,force:true});});fs.mkdirSync(path.join(root,'Defs'));fs.mkdirSync(path.join(root,'.atlas'));fs.writeFileSync(path.join(root,'Defs/a.xml'),'<Defs>\n  Armor\n  armor\n</Defs>');fs.writeFileSync(path.join(root,'.atlas/secret.txt'),'Armor');fs.writeFileSync(path.join(root,'Defs/b.txt'),'armor\n'.repeat(250));let result=await files.searchText(root,'Armor',{caseSensitive:true});assert.equal(result.matches.length,1);assert.equal(result.matches[0].line,2);assert.equal(result.matches[0].column,3);result=await files.searchText(root,'armor');assert.equal(result.matches.length,200);assert.equal(result.truncated,true);assert(!result.matches.some(x=>x.path.startsWith('.')));await assert.rejects(files.searchText(root,'armor',{signal:AbortSignal.abort()}),/cancelled/);await assert.rejects(files.searchText(root,'x'.repeat(301)),/300/);});
test('activity lifecycle handles successful retry, cancelled index, bounded logs and clearing only finished work',()=>{let now=0;const tasks=new Tasks(()=>{},()=>++now);tasks.observeAgent('a',{type:'agent_start'},'Test task');tasks.observeAgent('a',{type:'message_end',message:{role:'assistant',stopReason:'error',errorMessage:'Retryable'}});tasks.observeAgent('a',{type:'auto_retry_start'});tasks.observeAgent('a',{type:'message_end',message:{role:'assistant',stopReason:'stop'}});tasks.observeAgent('a',{type:'agent_end'});assert.equal(tasks.items.get('chat:a').status,'completed');tasks.observeIndex({type:'starting'});tasks.update('index:rimworld',{cancelRequested:true});tasks.observeIndex({type:'error',message:'abort'});assert.equal(tasks.items.get('index:rimworld').status,'cancelled');tasks.update('active',{kind:'chat',status:'running'});for(let i=0;i<100;i++)tasks.update('active',{},'Log '+i);assert.equal(tasks.items.get('active').logs.length,80);tasks.clear();assert.deepEqual(tasks.status().map(x=>x.id),['active']);tasks.dispose();});
test('manual compaction and compiler events settle in the activity center without a chat turn',()=>{const tasks=new Tasks();tasks.observeAgent('a',{type:'compaction_start'},'Compact');tasks.observeAgent('a',{type:'compaction_end'});assert.equal(tasks.items.get('chat:a').status,'completed');tasks.observeAgent('a',{type:'tool_execution_start',toolName:'build_mod',toolCallId:'b'});tasks.observeAgent('a',{type:'tool_execution_end',toolName:'build_mod',toolCallId:'b',isError:true,result:{content:[{type:'text',text:'Compiler failed'}]}});assert.equal(tasks.items.get('build:a:b').status,'failed');assert.match(tasks.items.get('build:a:b').logs.at(-1).text,/Compiler failed/);tasks.dispose();});
