const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const files=require('../src/atlas/project-files.cjs'),bulk=require('../src/atlas/bulk-assets.cjs'),{validateManifest}=require('../src/atlas/adapter-manifest.cjs');
const fixtureBase=path.resolve(__dirname,'../build-check/fixtures');fs.mkdirSync(fixtureBase,{recursive:true});
function fixture(t){const root=fs.mkdtempSync(path.join(fixtureBase,'workspace-'));t.after(()=>{assert(root.startsWith(fixtureBase+path.sep));fs.rmSync(root,{recursive:true,force:true})});return root;}
test('editor detects external changes and refuses escapes and linked paths',t=>{const root=fixture(t);fs.writeFileSync(path.join(root,'a.xml'),'<a/>');const initial=files.readText(root,'a.xml');fs.writeFileSync(path.join(root,'a.xml'),'<changed/>');assert.throws(()=>files.saveText(root,'a.xml','<new/>',initial.hash),/changed/);assert.equal(fs.readFileSync(path.join(root,'a.xml'),'utf8'),'<changed/>');assert.throws(()=>files.readText(root,'../secret.xml'),/path/);assert.throws(()=>files.readText(root,'C:/secret.xml'),/path/);fs.mkdirSync(path.join(root,'outside'));fs.symlinkSync(path.join(root,'outside'),path.join(root,'linked'),'junction');assert.throws(()=>files.safePath(root,'linked/a.xml'),/Linked/);});
test('bulk preview matches exact paths, skips invalid images and detects changes before writes',t=>{const root=fixture(t),target=path.join(root,'mod'),source=path.join(root,'incoming'),backup=path.join(root,'backups');fs.mkdirSync(path.join(target,'Textures'),{recursive:true});fs.mkdirSync(path.join(source,'Textures'),{recursive:true});const png=Buffer.from([137,80,78,71,13,10,26,10,0,1]);fs.writeFileSync(path.join(target,'Textures/a.png'),'old');fs.writeFileSync(path.join(source,'Textures/a.png'),png);fs.writeFileSync(path.join(source,'Textures/b.png'),'wrong');const req=[{path:'Textures/a.png'},{path:'Textures/a.png'},{path:'Textures/b.png'}];const plan=bulk.planAssets(target,source,['Textures/a.png','Textures/b.png'],req);assert.equal(plan.rows[0].references,2);assert.equal(plan.rows[1].issue,'Invalid PNG');fs.writeFileSync(path.join(target,'Textures/a.png'),'changed');assert.throws(()=>bulk.applyAssets(plan,backup),/changed/);assert.equal(fs.readFileSync(path.join(target,'Textures/a.png'),'utf8'),'changed');const newPlan=bulk.planAssets(target,source,['Textures/a.png'],req),result=bulk.applyAssets(newPlan,backup);assert.equal(result.count,1);assert.equal(fs.readFileSync(path.join(result.backup,'Textures/a.png'),'utf8'),'changed');assert.deepEqual(fs.readFileSync(path.join(target,'Textures/a.png')),png);});
test('bulk replacement rejects unrelated paths and expired previews',t=>{const root=fixture(t);assert.throws(()=>bulk.planAssets(root,root,['Source/a.cs'],[{path:'Source/a.cs'}]),/Only scanned/);assert.throws(()=>bulk.applyAssets({createdAt:0},root),/expired/)});
test('asynchronous file browsing skips private, build-cache and linked content',async t=>{const root=fixture(t);fs.mkdirSync(path.join(root,'Defs'));fs.writeFileSync(path.join(root,'Defs/a.xml'),'<Defs/>');fs.writeFileSync(path.join(root,'image.png'),'image');for(const name of ['.atlas','bin','obj','node_modules']){fs.mkdirSync(path.join(root,name));fs.writeFileSync(path.join(root,name,'private.txt'),'hidden');}const outside=fs.mkdtempSync(path.join(fixtureBase,'outside-'));t.after(()=>{assert(outside.startsWith(fixtureBase+path.sep));fs.rmSync(outside,{recursive:true,force:true})});fs.writeFileSync(path.join(outside,'secret.txt'),'secret');fs.symlinkSync(outside,path.join(root,'linked'),'junction');const result=await files.listFiles(root);assert.deepEqual(result.files,[{path:'Defs/a.xml',editable:true},{path:'image.png',editable:false}]);assert.equal(result.truncated,false);await assert.rejects(()=>files.listFiles(path.join(root,'linked')),/Linked/)});
test('future adapter manifests require supported versions and exclude Minecraft',()=>{const good={schemaVersion:1,apiVersion:1,id:'atlas-game-example',gameId:'example',name:'Example',version:'0.1.0',description:'Local test',gameVersions:['1.0']};assert.equal(validateManifest(good),good);assert.throws(()=>validateManifest({...good,gameId:'minecraft'}),/excluded/);assert.throws(()=>validateManifest({...good,apiVersion:999}),/API|apiVersion/);assert.throws(()=>validateManifest({...good,gameVersions:[]}),/versions/)});
function features(){let code=fs.readFileSync(path.resolve(__dirname,'../src/atlas/agent-features.ts'),'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export \{[\s\S]*?\};\s*$/,'');const ctx={console,require,process,Buffer,setTimeout,clearTimeout,AbortController,AbortSignal,Date,crypto,path,loadSettings:()=>({openaiSpeed:'fast'}),saveSettings:x=>x,pi:{estimateTokens:()=>10},k:{app:{isReady:()=>true},BrowserWindow:{getAllWindows:()=>[]}},getConversation:()=>null,toPiThinking:model=>({model,level:'high'}),buildAttachedPrompt:async(_e,text)=>({promptText:text,images:[]})};vm.createContext(ctx);vm.runInContext(code,ctx);return ctx;}
test('ported steering retains draft if a request finishes during attachment preparation',async()=>{const c=features(),session={isIdle:false,agent:{state:{}},getSteeringMessages:()=>[],steer:async()=>assert.fail('must not start a new run')},host={sessions:new Map([['chat',{session}]])};c.buildAttachedPrompt=async()=>{session.isIdle=true;return {promptText:'steer'}};const result=await c.felixSteer(host,'chat','steer',[]);assert.equal(result.queued,false);assert.match(result.reason,/finished/)});
test('manual compaction refuses busy sessions and incomplete summaries',async()=>{const c=features();await assert.rejects(()=>c.felixCompactContext({sessions:new Map([['chat',{session:{isIdle:false,agent:{state:{}}}}]])},'chat'),/Finish or stop/);const session={_compactionAbortController:new AbortController()},stream=await c.felixProtectCompactionStream(session,async()=>({result:async()=>({stopReason:'aborted',content:[]})}))();await assert.rejects(()=>stream.result(),/previous context/)});
test('resuming follows the complete session settlement lifecycle',async()=>{const c=features(),calls=[],session={model:{provider:'other'},agent:{continue:async()=>calls.push('continue')},_handlePostAgentRun:async()=>false,_flushPendingBashMessages:()=>calls.push('flush'),_emitAgentSettled:async()=>{calls.push('settled');session._isAgentRunActive=false}};await c.felixContinueSession(session);assert.deepEqual(calls,['continue','flush','settled']);assert.equal(session._isAgentRunActive,false)});
test('a model stream with no completion is recoverable and does not leave a hanging result',async()=>{const c=features(),source=()=>({async *[Symbol.asyncIterator](){yield {type:'start',partial:{content:[]}}}}),stream=c.felixGuardStream(source,30)({id:'fixture',provider:'fixture',api:'fixture'},{}),events=[];for await(const event of stream)events.push(event);const result=await stream.result();assert.equal(result.stopReason,'aborted');assert.match(result.errorMessage,/completion/);assert.equal(events.at(-1).type,'error')});

function queuedSession(messages,visible=messages.map(message=>message.content.filter(block=>block.type==='text').map(block=>block.text).join('\n'))){
 const followUp=[{role:'user',content:[{type:'text',text:'Later request'}]}],session={isIdle:false,agent:{steeringQueue:{messages},followUpQueue:{messages:followUp}},getSteeringMessages:()=>visible,_emitQueueUpdate:()=>{session.updates++},updates:0};return {session,followUp,host:{sessions:new Map([['chat',{session}]])}};
}
const instruction=(text,image)=>({role:'user',content:[{type:'text',text},...(image?[{type:'image',data:image,mimeType:'image/png'}]:[])]});
test('cancels one queued steering message with its image and preserves active work and unrelated queues',()=>{
 const c=features(),first=instruction('First','image-a'),second=instruction('Second','image-b'),{session,host,followUp}=queuedSession([first,second]);const items=c.felixSteeringItems(session);
 const result=c.felixCancelSteering(host,'chat',[items[0].id]);assert.equal(result.cancelled,1);assert.equal(session.agent.steeringQueue.messages.length,1);assert.equal(session.agent.steeringQueue.messages[0],second);assert.equal(session.getSteeringMessages()[0],'Second');assert.equal(session.agent.followUpQueue.messages,followUp);assert.equal(session.isIdle,false);assert.equal(session.updates,1);assert.equal(result.steeringItems[0].id,items[1].id);
});
test('stale cancellation cannot remove consumed steering or a different identical instruction',()=>{
 const c=features(),text='Identical instruction '.repeat(60),first=instruction(text,'image-a'),second=instruction(text,'image-b'),{session,host}=queuedSession([first,second]);const items=c.felixSteeringItems(session);assert.notEqual(items[0].id,items[1].id);
 session.agent.steeringQueue.messages.shift();const stale=c.felixCancelSteering(host,'chat',[items[0].id]);assert.equal(stale.cancelled,0);assert.match(stale.reason,/already being applied/);assert.equal(session.agent.steeringQueue.messages[0],second);assert.equal(session.getSteeringMessages().length,2);
 const current=c.felixCancelSteering(host,'chat',[items[1].id]);assert.equal(current.cancelled,1);assert.equal(session.agent.steeringQueue.messages.length,0);assert.equal(session.getSteeringMessages().length,1);
});
test('Cancel all removes only the displayed snapshot and leaves newly queued instructions intact',()=>{
 const c=features(),{session,host}=queuedSession([instruction('First'),instruction('Second')]);const ids=c.felixSteeringItems(session).map(item=>item.id),added=instruction('Added later');session.agent.steeringQueue.messages.push(added);session.getSteeringMessages().push('Added later');
 const result=c.felixCancelSteering(host,'chat',ids);assert.equal(result.cancelled,2);assert.equal(session.agent.steeringQueue.messages[0],added);assert.equal(session.getSteeringMessages()[0],'Added later');assert.throws(()=>c.felixCancelSteering(host,'chat',[]),/Choose queued/);
});
test('steering cancellation works with the actual bundled agent queue without a model call',async()=>{
 const runtime=process.env.ATLAS_RUNTIME_BASE||path.join(__dirname,'../dist/Atlas-0.1.0-release');
 const {Agent}=await import(require('node:url').pathToFileURL(path.resolve(runtime,'resources/node_modules/@earendil-works/pi-agent-core/dist/agent.js')).href);
 const c=features(),one=instruction('First'),two=instruction('Second','image'),{session,host}=queuedSession([one,two]);const agent=new Agent({streamFn:()=>assert.fail('No model call is allowed')});agent.steer(one);agent.steer(two);agent.followUp(instruction('Later'));session.agent=agent;
 const ids=c.felixSteeringItems(session).map(item=>item.id);const result=c.felixCancelSteering(host,'chat',[ids[0]]);assert.equal(result.cancelled,1);assert.equal(agent.steeringQueue.messages[0],two);assert.equal(agent.followUpQueue.messages.length,1);assert.equal(agent.hasQueuedMessages(),true);
});
