'use strict';
const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function read(buffer){const raw=buffer.subarray(16,16+buffer.readUInt32LE(12)),header=JSON.parse(raw),offset=8+buffer.readUInt32LE(4),files=[];function walk(node,prefix=''){for(const[name,entry]of Object.entries(node.files??{})){const namePath=prefix?prefix+'/'+name:name;if(entry.files)walk(entry,namePath);else if(!entry.unpacked&&entry.offset!==undefined){const start=offset+Number(entry.offset);files.push({name:namePath,entry,bytes:buffer.subarray(start,start+entry.size)});}}}walk(header);return{raw,header,files};}
function write(parsed){let offset=0;for(const file of parsed.files){file.entry.offset=String(offset);file.entry.size=file.bytes.length;offset+=file.bytes.length;const blockSize=4194304;file.entry.integrity={algorithm:'SHA256',hash:sha(file.bytes),blockSize,blocks:[]};for(let n=0;n<file.bytes.length;n+=blockSize)file.entry.integrity.blocks.push(sha(file.bytes.subarray(n,n+blockSize)));}
 const raw=Buffer.from(JSON.stringify(parsed.header)),padding=Math.ceil(raw.length/4)*4,prefix=Buffer.alloc(16+padding);prefix.writeUInt32LE(4,0);prefix.writeUInt32LE(8+padding,4);prefix.writeUInt32LE(4+padding,8);prefix.writeUInt32LE(raw.length,12);raw.copy(prefix,16);return Buffer.concat([prefix,...parsed.files.map(f=>f.bytes)]);}
function add(parsed,name,bytes){let node=parsed.header;const parts=name.split('/');for(const part of parts.slice(0,-1)){node.files??={};node.files[part]??={files:{}};node=node.files[part];}const entry={size:bytes.length,offset:'0'};node.files[parts.at(-1)]=entry;parsed.files.push({name,entry,bytes});}
function patchExe(bytes,oldHash,newHash){const pe=bytes.readUInt32LE(0x3c);assert.equal(bytes.toString('ascii',pe,pe+4),'PE\0\0');const optional=pe+24,magic=bytes.readUInt16LE(optional),directories=optional+(magic===0x20b?112:96),sections=optional+bytes.readUInt16LE(pe+20),rva=bytes.readUInt32LE(directories+16),size=bytes.readUInt32LE(directories+20);let resource;for(let i=0;i<bytes.readUInt16LE(pe+6);i++){const section=sections+i*40,base=bytes.readUInt32LE(section+12),length=bytes.readUInt32LE(section+16);if(rva>=base&&rva<base+length)resource=bytes.readUInt32LE(section+20)+rva-base;}
 const at=bytes.indexOf(Buffer.from(oldHash),resource);assert(at>=resource&&at+64<=resource+size,'ASAR hash resource missing');assert.equal(bytes.indexOf(Buffer.from(oldHash),at+64),-1);const output=Buffer.from(bytes);output.write(newHash,at,64,'ascii');output.fill(0,directories+32,directories+40);const checksumOffset=optional+64;output.writeUInt32LE(0,checksumOffset);let checksum=0;for(let i=0;i<output.length;i+=2){checksum+=output[i]+((output[i+1]??0)<<8);checksum=(checksum&65535)+(checksum>>>16);}checksum=((checksum&65535)+(checksum>>>16)+output.length)>>>0;output.writeUInt32LE(checksum,checksumOffset);const sentinel=Buffer.from('dL7pKGdnNz796PbbjQWNKmHXBZaB9tsX'),fuse=output.indexOf(sentinel)+sentinel.length;assert.equal(output[fuse+6],49);assert.equal(output[fuse+7],49);return output;}
module.exports={read,write,add,patchExe,sha};
