import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import crypto from 'node:crypto';import {createRequire} from 'node:module';
import {build} from '../../build-tools/native/node_modules/vite/dist/node/index.js';import react from '../../build-tools/native/node_modules/@vitejs/plugin-react/dist/index.js';import tailwind from '../../build-tools/native/node_modules/@tailwindcss/vite/dist/index.mjs';
const require=createRequire(import.meta.url),{Library,sha}=require('../../src/atlas/library.cjs'),{ApplicationUpdate}=require('../../src/atlas/application-update.cjs'),{Tasks}=require('../../src/atlas/tasks.cjs'),files=require('../../src/atlas/project-files.cjs'),{sign}=require('./publish-packs.cjs');
const root=process.cwd(),dir=path.join(root,'build-check/release-preview'),output=path.join(root,'build-check/release-preview-static');fs.mkdirSync(dir,{recursive:true});const profile=fs.mkdtempSync(path.join(dir,'fixture-')),resources=path.join(profile,'resources'),project=path.join(profile,'TestMod');fs.mkdirSync(resources);fs.mkdirSync(path.join(project,'Defs/Apparel'),{recursive:true});fs.mkdirSync(path.join(project,'Source'));
fs.writeFileSync(path.join(project,'Defs/Apparel/Armor.xml'),'<Defs>\n  <ThingDef ParentName="ApparelBase">\n    <defName>Atlas_ScaleArmor</defName>\n    <label>scale armor</label>\n    <description>Light armor with layered scales.</description>\n  </ThingDef>\n</Defs>\n');fs.writeFileSync(path.join(project,'Source/Armor.cs'),'using Verse;\n\nnamespace Atlas.Sample\n{\n    public class Armor : ThingComp\n    {\n        public override void CompTick()\n        {\n            base.CompTick();\n        }\n    }\n}\n');for(let i=0;i<500;i++)fs.writeFileSync(path.join(project,'Defs/Apparel/Fixture'+String(i).padStart(3,'0')+'.xml'),'<Defs />');
const keys=crypto.generateKeyPairSync('ed25519');fs.writeFileSync(path.join(resources,'trust.json'),JSON.stringify({keys:{'atlas-local-1':keys.publicKey.export({format:'pem',type:'spki'})}}));const bytes=Buffer.alloc(16_000_000,42),entry={version:'0.3.0',file:'fixture.zip',size:bytes.length,sha256:sha(bytes)},envelope=sign({type:'feed',sequence:1,issuedAt:Date.now()-1000,expiresAt:Date.now()+86400000,packs:[],application:entry},keys.privateKey),clients=new Set();
function emit(kind,value){for(const client of clients)client.write('data: '+JSON.stringify({kind,value})+'\n\n');}
const tasks=new Tasks(value=>emit('tasks',value));const library=new Library(profile,resources,{fetch:async(url,options)=>{if(String(url).endsWith('index.atlas.json'))return new Response(envelope);const start=Number(options.headers?.Range?.match(/\d+/)?.[0]??0);return {ok:true,status:start?206:200,headers:new Headers(start?{'content-range':`bytes ${start}-${bytes.length-1}/${bytes.length}`}:{'content-length':String(bytes.length)}),body:(async function*(){for(let at=start;at<bytes.length;at+=500_000){await new Promise(resolve=>setTimeout(resolve,300));options.signal.throwIfAborted();yield bytes.subarray(at,at+500_000);}})()};}});library.configure({source:'https://example.com/fixture/'});const application=new ApplicationUpdate(library,{app:{}},()=>false,{onState:state=>{tasks.observeDownload(state);emit('app',state);}});
tasks.observeIndex({type:'starting'});tasks.observeIndex({type:'phase',phase:'decompile',message:'Decompiling Assembly-CSharp.dll…',fraction:0.42});tasks.observeAgent('sample',{type:'agent_start'},'Review armor definitions');tasks.observeAgent('sample',{type:'tool_execution_start',toolName:'build_mod',toolCallId:'build'});tasks.observeAgent('sample',{type:'tool_execution_end',toolName:'build_mod',toolCallId:'build',isError:true,result:{content:[{type:'text',text:'Fixture compiler: error CS0246: check the referenced type. This is a UI demonstration.'}]}});
fs.writeFileSync(path.join(dir,'index.html'),'<!doctype html><html data-theme="dark"><head><meta charset="UTF-8"><title>Atlas 0.2.6 preview</title></head><body><div id="root"></div><script type="module" src="./fixture.tsx"></script></body></html>');
fs.writeFileSync(path.join(dir,'fixture.tsx'),`import React,{useEffect} from 'react';import {createRoot} from 'react-dom/client';import {FilesView} from '../../src/atlas/files-view';import {AtlasActivityButton} from '../../src/atlas/activity-center';import {AtlasApplicationUpdates} from '../../src/atlas/application-updates';import {AppDialog} from '../../src/components/app-dialog';import '../../src/styles.css';
const api=async(route:string,data:any={})=>{const response=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),value=await response.json();if(!response.ok)throw new Error(value.error);return value;};const listen=(kind:string,fn:any)=>{const events=new EventSource('/api/events');events.onmessage=e=>{const data=JSON.parse(e.data);if(data.kind===kind)fn(data.value);};return()=>events.close();};
window.modmixer={projectDraftState:async()=>{},projectFiles:()=>api('files'),projectRead:(_folder:any,file:string)=>api('read',{file}),projectSave:(_folder:any,file:string,text:string,hash:string)=>api('save',{file,text,hash}),projectSearch:(_folder:any,query:string,options:any)=>api('search',{query,options}),projectSearchCancel:async()=>{},projectReveal:async()=>{},onModChanged:()=>()=>{},atlasTasksStatus:()=>api('tasks'),atlasTaskAction:(id:string,action:string)=>api('task-action',{id,action}),atlasTasksClear:()=>api('clear'),onAtlasTasksState:(fn:any)=>listen('tasks',fn),atlasAppStatus:()=>api('status'),atlasAppCheck:()=>api('check'),atlasAppDownload:()=>api('download'),atlasAppPause:()=>api('pause'),atlasAppCancel:()=>api('cancel'),atlasAppInstall:()=>api('install'),onAtlasAppState:(fn:any)=>listen('app',fn)} as any;
function Fixture(){useEffect(()=>{document.querySelector('details.atlas-source-settings')!.open=true;},[]);return <main style={{height:'100vh',display:'flex',flexDirection:'column',background:'var(--paper)'}}><header className="atlas-pane-heading"><strong>Atlas 0.2.6 · Test project</strong><div className="atlas-actions"><span style={{color:'var(--muted)'}}>Context 200k / 1.05M</span><AtlasActivityButton/></div></header><section style={{display:'flex',flex:1,minHeight:0}}><div style={{flex:1,minWidth:0,display:'flex'}}><FilesView mod={{folder:'TestMod'} as any} busy={false}/></div><aside style={{width:360,padding:18,overflow:'auto',borderLeft:'1px solid var(--line)'}}><h2>Updates</h2><p style={{fontSize:12,color:'var(--muted)',marginBottom:14}}>Synthetic project and signed test download. Installation is simulated.</p><AtlasApplicationUpdates/></aside></section><AppDialog/></main>};createRoot(document.getElementById('root')!).render(<Fixture/>);`);
await build({configFile:false,root,base:'./',plugins:[react(),tailwind()],resolve:{alias:{'@':path.join(root,'src')}},build:{outDir:output,emptyOutDir:true,rollupOptions:{input:path.join(dir,'index.html')}}});
http.createServer(async(request,response)=>{const route=new URL(request.url,'http://localhost').pathname;if(route==='/api/events'){response.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache'});response.write('data: '+JSON.stringify({kind:'app',value:application.status()})+'\n\n');clients.add(response);request.on('close',()=>clients.delete(response));return;}
if(route.startsWith('/api/')){try{let raw='';for await(const chunk of request){raw+=chunk;if(raw.length>3_000_000)throw new Error('Too large');}const data=JSON.parse(raw||'{}');let value;switch(route.slice(5)){case'files':value=await files.listFiles(project);break;case'read':value=files.readText(project,data.file);break;case'save':value=files.saveText(project,data.file,data.text,data.hash);break;case'search':value=await files.searchText(project,data.query,data.options);break;case'tasks':value=tasks.status();break;case'clear':tasks.clear();value={};break;case'task-action':if(data.id==='download:app'){value=data.action==='pause'?application.pause():data.action==='cancel'?application.cancel():data.action==='retry'?await application.download():application.status();}else{const task=tasks.items.get(data.id);tasks.update(data.id,{status:data.action==='cancel'?'cancelled':'running',phase:data.action==='cancel'?'Stopped':'Retrying'},'Preview action');value=tasks.status();}break;case'status':value=application.status();break;case'check':value=await application.check();break;case'download':value=await application.download();break;case'pause':value=application.pause();break;case'cancel':value=application.cancel();break;case'install':if(!application.ready)throw new Error('Download first');value={...application.status(),simulatedInstall:true};break;default:throw new Error('Unknown route');}response.setHeader('Content-Type','application/json');response.end(JSON.stringify(value));}catch(error){response.writeHead(400,{'Content-Type':'application/json'});response.end(JSON.stringify({error:error.message}));}return;}
const file=path.resolve(output,'.'+decodeURIComponent(route));if(!file.startsWith(output+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){response.writeHead(404);response.end();return;}response.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(response);}).listen(51943,'127.0.0.1',()=>console.log('Atlas release preview: http://127.0.0.1:51943/build-check/release-preview/index.html'));
