'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),out=path.resolve(root,'../outputs');
const version=JSON.parse(fs.readFileSync(path.join(root,'package.json'))).version;
const project=JSON.parse(fs.readFileSync(path.join(root,'atlas.project.json')));
project.version=version;
project.status='Atlas '+version+' native source release built and verified';
project.implementation.runtime='Atlas TypeScript/React application compiled from source; Electron, native bindings, connectors and public tools reused from an Atlas portable runtime';
project.implementation.sources='src, templates/game-adapter';
project.implementation.applicationRollback='Verified application replacement with backups; startup window/API health check and failed-startup rollback; private data retained; no data migrations';
project.implementation.newGames='Versioned source adapter interface and starter template; local manifests are informational until a reviewed adapter is compiled; RimWorld only';
project.repository='https://github.com/lordfelixmotosr/atlas';
project.libraryDesign.onlinePublishing='Signed GitHub Release assets from lordfelixmotosr/atlas; restricted release redirects, daily checks, offline starter feed retained';
project.buildPhases.push(version+': shared OpenAI account label validation; compact and hideable editor; virtualized asynchronous file browser; idle polling and refresh reduction');
project.acceptanceResults.passed.push(version+' source type checking and 63 automated tests passed','Native '+version+' Electron rendering, portable paths, signed packs, account login validation, asynchronous file browser, library IPC, reference viewer, synthetic bulk import and modification reports; no provider login or real mod edits',version+' portable and application ZIPs passed CRC, private-folder exclusion and receipt hash checks');
project.release=JSON.parse(fs.readFileSync(path.join(out,'Atlas-'+version+'-checksums.json')));
fs.writeFileSync(path.join(root,'atlas.project.json'),JSON.stringify(project,null,2)+'\n');
fs.copyFileSync(path.join(out,'Atlas-'+version+'-checksums.json'),path.join(root,'release-result.json'));
const application=project.release['application-update'];
fs.writeFileSync(path.join(root,'build-check/application-release.json'),JSON.stringify({version,file:path.basename(application.path),size:application.size,sha256:application.sha256},null,2));
fs.copyFileSync(path.resolve(out,application.path),path.join(out,'Atlas-update-feed',path.basename(application.path)));
require('./publish-packs.cjs').publish(path.join(root,'packs'),path.join(out,'Atlas-update-feed'),path.join(root,'release-tools/publisher.private.pem'),JSON.parse(fs.readFileSync(path.join(root,'build-check/application-release.json'))));
fs.writeFileSync(path.join(out,'Atlas-'+version+'-UPDATE.txt'),`Atlas ${version} — Felix\n\nFresh installation:\nExtract the portable ZIP into a new writable folder and run Atlas.exe.\n\nKeep an existing Atlas profile:\nClose Atlas. Back up your existing Atlas folder. Extract the contents inside the application-update ZIP's Atlas folder into the existing app folder. Keep data, custom, library and updates. Manual replacement does not run automatic startup recovery.\n\nSigned updater with startup recovery (Atlas 0.2.2 or newer):\nIf you have Atlas 0.2.1, first use the manual application-update ZIP once; its downloader cannot follow GitHub Release redirects.\nIn Knowledge & Skills, set Update source to:\nhttps://github.com/lordfelixmotosr/atlas/releases/latest/download/\nCheck app updates, then Download update and Restart and install when idle. Atlas 0.2.2 uses this online feed by default; custom sources and disabled automatic checks are preserved. The bundled updates folder remains available for offline use.\n\nNew in this release: fixed OpenAI account login; Compact editor, Hide editor and Hide files controls; desktop resizing down to a 260-pixel middle pane; virtualized file browsing beyond 300 rows; asynchronous scans and batched refreshes; stopped idle transcript polling. Task progress remains available. RimWorld only; no Minecraft integration.\n\nKnowledge and skill updates require reviewed versions published by the maintainer. Existing packs remain usable offline. Windows executable code signing is not included; update feeds and pack envelopes are signed separately.\n\nSee README-ATLAS.md for portability, credentials, source builds and validation details.\n`);
console.log('Recorded Atlas '+version+' release and refreshed its local signed feed.');
