const fs=require('node:fs'),path=require('node:path');const root=path.resolve(__dirname,'../..');const edit=(f,fn)=>{const p=path.join(root,f);fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n')))};
edit('src/components/build-view.tsx',s=>{
 s='import {useState,useRef,useEffect} from "react";\nimport {FilesView} from "../atlas/files-view";\n'+s;
 const marker='  // Pre-scaffold';const at=s.indexOf(marker);s=s.slice(0,at)+`  const [navigation,setNavigation]=useState(()=>localStorage.getItem('atlas.layout.navigation')!=='closed');
  const [chatWidth,setChatWidth]=useState(()=>Math.max(320,Math.min(700,Number(localStorage.getItem('atlas.layout.chatWidth'))||440)));
  const [chatVisible,setChatVisible]=useState(true);const workspace=useRef<HTMLDivElement>(null);
  useEffect(()=>{localStorage.setItem('atlas.layout.navigation',navigation?'open':'closed')},[navigation]);
  useEffect(()=>{localStorage.setItem('atlas.layout.chatWidth',String(chatWidth))},[chatWidth]);
  const resize=(x:number)=>{const box=workspace.current?.getBoundingClientRect();if(box)setChatWidth(Math.max(320,Math.min(700,box.right-x,box.width-420)))};
`+s.slice(at);
 s=s.replace('<div className="flex min-h-0 flex-1">','<div className="atlas-workspace flex min-h-0 flex-1" ref={workspace}>\n      <div className="atlas-navigation-toggle"><button className="atlas-icon-button" title={navigation?"Collapse navigation":"Expand navigation"} aria-label={navigation?"Collapse navigation":"Expand navigation"} onClick={()=>setNavigation(v=>!v)}>{navigation?"‹":"›"}</button></div>\n      <div className={navigation?"atlas-navigation":"hidden"}>');
 s=s.replace('      <div className="flex min-w-0 flex-1 flex-col">','      </div>\n      <div className="flex min-w-0 flex-1 flex-col">');
 s=s.replace("        {effectivePanel === 'schematic'",`        <div className="atlas-workspace-toolbar"><span>{effectivePanel==='chat'?'Project workspace':effectivePanel==='files'?'File editor':effectivePanel[0].toUpperCase()+effectivePanel.slice(1)}</span><button className="atlas-button" disabled={!activeMod} onClick={()=>setChatVisible(v=>!v)}>{chatVisible?'Hide chat':'Show chat'}</button></div>
        <div className="atlas-workspace-body">
        <div className="atlas-center-pane">
        {(effectivePanel==='files'||effectivePanel==='chat')&&activeMod&&<FilesView mod={activeMod} busy={busy}/>}
        {effectivePanel === 'schematic'`);
 const start=s.indexOf('        <div\n          className={\n            effectivePanel');const end=s.indexOf('          <ChatPanel',start);
 s=s.slice(0,start)+`        </div>
        {activeMod&&chatVisible&&<div role="separator" aria-label="Resize chat" aria-orientation="vertical" aria-valuenow={Math.round(chatWidth)} aria-valuemin={320} aria-valuemax={700} tabIndex={0} className="atlas-resize-handle" onKeyDown={e=>{if(e.key==='ArrowLeft'){e.preventDefault();setChatWidth(v=>Math.min(700,v+24))}if(e.key==='ArrowRight'){e.preventDefault();setChatWidth(v=>Math.max(320,v-24))}}} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))resize(e.clientX)}} onPointerUp={e=>e.currentTarget.releasePointerCapture(e.pointerId)}/>}
        <div className={chatVisible||!activeMod?'atlas-chat-pane':'hidden'} style={activeMod?{width:chatWidth}:undefined}>
          <div className="atlas-pane-heading"><strong>Atlas assistant</strong><span>Steer while working</span></div>
`+s.slice(end);
 s=s.replace('        </div>\n      </div>\n    </div>','        </div>\n        </div>\n      </div>\n    </div>');return s;
});
edit('src/components/mod-build-sidebar.tsx',s=>s.replace("  | 'chat'","  | 'files'\n  | 'chat'").replace('      <nav className="no-scrollbar flex-1 overflow-auto py-1">','      <nav className="no-scrollbar flex-1 overflow-auto py-1">\n        {mod&&<SidebarRow label="Files" subtitle="Browse and edit source" icon={<span aria-hidden>▤</span>} active={panel===\'files\'} onClick={()=>onSelectPanel(\'files\')} />}'));
edit('src/components/mod-header.tsx',s=>s.replace('<div className="ml-4 flex items-center gap-2">','<div className="ml-4 flex flex-wrap items-center gap-2">\n        <FelixSentenceShortcut conversationId={conversationId} />'));
edit('src/components/assets-view.tsx',s=>s.replace('<div className="mt-2 flex items-center gap-2">','<p className="atlas-asset-path" title={req.path}>{req.path}</p>\n        <div className="mt-2 flex flex-wrap items-center gap-2">\n          <button className="atlas-button" onClick={()=>void window.modmixer.revealAsset(folder,req.path).catch(e=>appAlert(String(e)))}>File location</button>').replace('        .then((url) => {','        .then((url) => {').replace('          if (!cancelled) setPreviewUrl(url);\n        });','          if (!cancelled) setPreviewUrl(url);\n        }).catch(()=>{if(!cancelled)setPreviewUrl(null)});'));
edit('src/components/app-settings-dialog.tsx',s=>'import {FelixOpenAIAccounts,FelixSpeedControl,FelixUsageControl,FelixAccountControl} from "../atlas/controls";\nimport {AtlasApplicationUpdates} from "../atlas/library-ui";\n'+s.replace('          <ProviderRow\n            key={link.id}','          <ProviderRow\n            key={link.id}') .replace('{links.map((link) => (\n          <ProviderRow','{links.map((link) => (\n          link.id==="openai-codex"?<FelixOpenAIAccounts key={link.id} busy={busyId===link.id} progress={progress?.providerId===link.id?progress:null} prompt={prompt?.providerId===link.id?prompt:null} onCancel={onCancel}/>:<ProviderRow'));
// Preserve internal storage and IPC identifiers; change text presented in the UI and system prompt.
const ts=require(path.join(root,'build-tools/native/node_modules/typescript'));function walkdir(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory()&&!e.name.startsWith('__tests__'))walkdir(p);else if(/\.tsx?$/.test(e.name)&&!p.includes('atlas'+path.sep+'agent-features')){const s=fs.readFileSync(p,'utf8'),tree=ts.createSourceFile(p,s,ts.ScriptTarget.Latest,true),edits=[];function visit(n){if(ts.isJsxText(n)){const text=n.getFullText(tree);if(/modmixer/i.test(text))edits.push([n.pos,n.end,text.replace(/modmixer/ig,'Atlas')]);}else if(ts.isStringLiteral(n)||ts.isNoSubstitutionTemplateLiteral(n)){const t=n.text;if(/modmixer/i.test(t)&&!/(?:modmixer[:/.]|\.modmixer|modmixer-|modmixer@|\bmodmixer\b.*github|https?:|\/)/i.test(t)&&!t.startsWith('modmixer')){edits.push([n.getStart(tree),n.end,JSON.stringify(t.replace(/modmixer/ig,'Atlas'))]);}}ts.forEachChild(n,visit)}visit(tree);let next=s;for(const [a,b,t]of edits.sort((a,b)=>b[0]-a[0]))next=next.slice(0,a)+t+next.slice(b);if(edits.length)fs.writeFileSync(p,next);}}}walkdir(path.join(root,'src'));
