import {useEffect,useRef,useState} from 'react';
type Task={id:string;kind:string;title:string;status:string;phase:string;fraction:number|null;startedAt:number;updatedAt:number;endedAt?:number;conversationId?:string;canRetry?:boolean;logs:{at:number;text:string}[]};
function duration(ms:number){const seconds=Math.max(0,Math.floor(ms/1000));return seconds>=60?`${Math.floor(seconds/60)}m ${seconds%60}s`:`${seconds}s`;}
export function AtlasActivityButton(){
 const [tasks,setTasks]=useState<Task[]>([]),[open,setOpen]=useState(false),[now,setNow]=useState(Date.now()),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[working,setWorking]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{let alive=true;window.modmixer.atlasTasksStatus().then(value=>alive&&setTasks(value)).catch(e=>alive&&setError(e.message));const off=window.modmixer.onAtlasTasksState((value:Task[])=>alive&&setTasks(value));return()=>{alive=false;off();};},[]);
 useEffect(()=>{if(open){dialog.current?.showModal();setNow(Date.now());const timer=setInterval(()=>{if(!document.hidden)setNow(Date.now());},1000);return()=>clearInterval(timer);}dialog.current?.close();},[open]);
 async function action(id:string,operation:string){setWorking(id);setError('');try{await window.modmixer.atlasTaskAction(id,operation);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setWorking('');}}
 const active=tasks.filter(task=>task.status==='running').length,visible=tasks.filter(task=>filter==='all'||(filter==='active'?task.status==='running':task.status!=='running'));
 return <><button className="atlas-button" onClick={()=>setOpen(true)}>Activity{active>0?' · '+active:''}</button><dialog ref={dialog} className="atlas-activity-dialog" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><header><div><h2>Activity</h2><p>{active} running · Recent tasks stay here until Atlas closes.</p></div><button className="atlas-icon-button" aria-label="Close activity" onClick={()=>setOpen(false)}>×</button></header><div className="atlas-actions"><select aria-label="Filter activity" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All tasks</option><option value="active">Running</option><option value="recent">Recent</option></select><button className="atlas-button" onClick={()=>void window.modmixer.atlasTasksClear().catch(e=>setError(e.message))}>Clear finished</button></div>{error&&<p className="atlas-warning" role="alert">{error}</p>}<div className="atlas-activity-list">{visible.map(task=><article key={task.id} className={'atlas-task-card atlas-task-'+task.status}><div className="atlas-task-title"><strong>{task.title}</strong><span>{task.status}</span></div><p role="status">{task.phase}</p>{task.status==='running'||task.kind==='download'?<>{task.fraction===null?<div className="atlas-task-progress" role="progressbar" aria-label={task.phase} aria-valuetext={task.phase}><span/></div>:<progress aria-label={task.phase} max={1} value={task.fraction}/>}</>:null}<small>{task.fraction!==null?Math.floor(task.fraction*100)+(task.kind==='index'?'% of this stage · ':'% · '):''}{duration((task.endedAt??now)-task.startedAt)} elapsed · {task.status==='running'?'Last activity '+duration(now-task.updatedAt)+' ago':new Date(task.endedAt??task.updatedAt).toLocaleTimeString()}</small><div className="atlas-actions">
 {task.status==='running'&&<button className="atlas-button" disabled={!!working} onClick={()=>void action(task.id,task.kind==='download'?'pause':'cancel')}>{working===task.id?'Stopping…':task.kind==='download'?'Pause':task.kind==='build'?'Stop chat':'Stop'}</button>}
 {['failed','cancelled','paused'].includes(task.status)&&task.kind!=='build'&&task.canRetry!==false&&<button className="atlas-button" disabled={!!working} onClick={()=>void action(task.id,'retry')}>{task.kind==='download'?'Resume download':task.kind==='chat'?'Resume chat':'Retry'}</button>}
 {task.kind==='download'&&task.phase==='Ready to install'&&<button className="atlas-button atlas-primary" disabled={!!working} onClick={()=>void action(task.id,'install')}>Install and restart</button>}
 {task.kind==='download'&&['paused','failed'].includes(task.status)&&<button className="atlas-button" disabled={!!working} onClick={()=>void action(task.id,'cancel')}>Discard download</button>}
 </div><details><summary>Task log · {task.logs.length} entries</summary><pre>{task.logs.map(log=>new Date(log.at).toLocaleTimeString()+' '+log.text).join('\n')}</pre></details></article>)}{!visible.length&&<div className="atlas-empty"><h3>No tasks here yet</h3><p>AI work, builds, reference indexing, and application downloads appear here.</p></div>}</div></dialog></>;
}
