import {useEffect,useState} from 'react';
import type {WorkspaceMod} from '../agent/workspace';
import {appConfirm} from '../components/app-dialog';
export function FilesView({mod,busy}:{mod:WorkspaceMod;busy:boolean}){
 const [files,setFiles]=useState<any[]>([]),[query,setQuery]=useState(''),[current,setCurrent]=useState<any>(null),[draft,setDraft]=useState(''),[error,setError]=useState(''),[working,setWorking]=useState(false),[notice,setNotice]=useState('');
 const dirty=!!current&&draft!==current.text;
 const refresh=async()=>{try{const result=await window.modmixer.projectFiles(mod.folder);setFiles(result.files);setNotice(result.truncated?'File list capped at 10,000. Open the folder for the remaining files.':'')}catch(e){setError(String(e))}};
 useEffect(()=>{void refresh();return window.modmixer.onModChanged(({folder})=>{if(folder===mod.folder)void refresh()})},[mod.folder]);
 const open=async(file:string)=>{if(dirty&&!await appConfirm('Discard your unsaved edits to open another file?',{okLabel:'Discard edits',tone:'danger'}))return;setWorking(true);setError('');try{const result=await window.modmixer.projectRead(mod.folder,file);setCurrent(result);setDraft(result.text)}catch(e){setError(String(e))}finally{setWorking(false)}};
 const save=async()=>{if(!current)return;setWorking(true);setError('');try{const result=await window.modmixer.projectSave(mod.folder,current.path,draft,current.hash);setCurrent(result);setNotice('Saved '+result.path)}catch(e){setError(String(e))}finally{setWorking(false)}};
 const filtered=files.filter(f=>f.path.toLowerCase().includes(query.toLowerCase()));
 return <section className="atlas-files"><aside className="atlas-file-tree"><div className="atlas-pane-heading"><strong>Project files</strong><button className="atlas-icon-button" onClick={()=>void refresh()} title="Refresh files" aria-label="Refresh files">↻</button></div><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Find project file" placeholder="Find a file…"/><div className="atlas-file-list">{filtered.slice(0,300).map(f=><button key={f.path} title={f.path} className={current?.path===f.path?'active':''} onClick={()=>f.editable?void open(f.path):void window.modmixer.projectReveal(mod.folder,f.path)}><span>{f.editable?'▤':'◇'}</span>{f.path}</button>)}{!filtered.length&&<p>No files match your search.</p>}{filtered.length>300&&<p>Refine your search to see more files.</p>}</div><button className="atlas-button" onClick={()=>void window.modmixer.projectReveal(mod.folder)}>Open project folder</button></aside><div className="atlas-editor"><div className="atlas-pane-heading"><span title={current?.path}>{current?.path||'File editor'}{dirty?' • Unsaved':''}</span><div className="atlas-actions"><button className="atlas-button" disabled={!current||working} onClick={()=>void open(current.path)}>Reload</button><button className="atlas-button atlas-primary" disabled={!dirty||busy||working} onClick={()=>void save()} title={busy?'Finish active work before saving':'Save this file'}>{working?'Working…':'Save'}</button></div></div>{error&&<p role="alert" className="atlas-warning">{error}</p>}{notice&&<p className="atlas-inline-notice" role="status">{notice}</p>}{current?<textarea spellCheck={false} aria-label={'Edit '+current.path} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();if(dirty&&!busy&&!working)void save()}}}/>:<div className="atlas-empty"><span>▤</span><h2>Your project, in view</h2><p>Choose an XML, C#, or text file to edit. Keep your conversation open alongside it.</p><p>Images and binary files open in their file location.</p></div>}</div></section>
}
