// @ts-nocheck
import {AdaptersSection} from "./adapters-ui";
import * as v from "react";import * as s from "react/jsx-runtime";
function AtlasApplicationUpdates(){
 const [value,setValue]=v.useState(null),[error,setError]=v.useState(''),[busy,setBusy]=v.useState(false);
 v.useEffect(()=>{let alive=true;window.modmixer.atlasAppStatus().then(value=>alive&&setValue(value)).catch(e=>alive&&setError(e.message));const off=window.modmixer.onAtlasAppState(value=>alive&&setValue(value));return()=>{alive=false;off();};},[]);
 async function action(fn){setBusy(true);setError('');try{setValue(await fn());}catch(e){setError(e.message);}finally{setBusy(false);}}
 return s.jsxs('details',{className:'atlas-source-settings',children:[s.jsx('summary',{children:'Atlas application updates'}),s.jsx('p',{children:'Atlas '+(value?.version??'0.2.0')+' portable · checked daily with your library. Verified app updates download automatically; you choose when to restart.'}),(error||value?.error)&&s.jsx('p',{role:'alert',className:'atlas-error',children:error||value.error}),value?.ready?s.jsx('p',{className:'atlas-notice',children:'Version '+value.ready+' is verified and ready.'}):value?.available?s.jsx('p',{children:'Version '+value.available+' is available.'}):s.jsx('p',{children:'Updates from '+(value?.source??'the selected signed feed')+'.'}),value?.recovery&&s.jsx('p',{className:value.recovery.status==='rolled-back'?'atlas-warning':'atlas-notice',children:value.recovery.reason||'Last update started successfully.'}),value?.lastCheckedAt&&s.jsx('p',{children:'Last check: '+new Date(value.lastCheckedAt).toLocaleString()}),s.jsxs('div',{className:'atlas-actions',children:[s.jsx('button',{type:'button',className:'atlas-action',disabled:busy||value?.working,onClick:()=>void action(()=>window.modmixer.atlasAppCheck()),children:busy||value?.working?'Working…':'Check app updates'}),value?.available&&!value?.ready&&s.jsx('button',{type:'button',className:'atlas-action',disabled:busy,onClick:()=>void action(()=>window.modmixer.atlasAppDownload()),children:'Download update'}),value?.ready&&s.jsx('button',{type:'button',className:'atlas-action atlas-primary',disabled:busy,onClick:()=>void action(()=>window.modmixer.atlasAppInstall()),children:'Restart and install'})]})]});
}
function AtlasKnowledgeButton(){
  const [open,setOpen]=v.useState(false),[status,setStatus]=v.useState(null),[error,setError]=v.useState(''),[pending,setPending]=v.useState(''),[query,setQuery]=v.useState(''),[results,setResults]=v.useState([]),[source,setSource]=v.useState(''),[notice,setNotice]=v.useState('');
  const button=v.useRef(null),dialog=v.useRef(null),alive=v.useRef(true);
  v.useEffect(()=>{alive.current=true;window.modmixer.atlasLibraryStatus().then(value=>{if(alive.current){setStatus(value);setSource(value.config.source);}}).catch(e=>alive.current&&setError(e.message));const off=window.modmixer.onAtlasLibraryState(value=>{if(alive.current)setStatus(value);});return()=>{alive.current=false;off();};},[]);
  const close=()=>{setOpen(false);button.current?.focus();};
  v.useEffect(()=>{if(!open)return;dialog.current?.focus();const key=e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const list=Array.from(dialog.current?.querySelectorAll('button:not(:disabled),input:not(:disabled),a[href],[tabindex="0"]')??[]);if(!list.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[open]);
  async function run(label,fn,message){if(pending)return;setPending(label);setError('');setNotice('');try{const value=await fn();if(value?.packs)setStatus(value);if(message)setNotice(typeof message==='function'?message(value):message);}catch(e){setError(e.message??String(e));}finally{setPending('');}}
  const h=s.jsx,j=s.jsxs,buttonProps={type:'button',className:'atlas-action',disabled:!!pending||status?.working};
  const date=value=>value?new Date(value).toLocaleString():'Not checked yet';
  const statusLabel=status?.config.lastError?'Update needs attention':status?.packs.some(pack=>pack.pending)?'Update waiting':status?.packs.length+' packs';
  return j(s.Fragment,{children:[h('button',{ref:button,type:'button',className:'atlas-library-launch',onClick:()=>setOpen(true),title:'Manage knowledge, coding skills and image references',children:'Knowledge & Skills'}),open&&h('div',{className:'atlas-overlay',onMouseDown:e=>{if(e.target===e.currentTarget)close();},children:j('section',{ref:dialog,role:'dialog','aria-modal':true,'aria-labelledby':'atlas-library-title',tabIndex:-1,className:'atlas-dialog',children:[
    j('header',{className:'atlas-dialog-head',children:[j('div',{children:[h('h2',{id:'atlas-library-title',children:'Knowledge & Skills'}),h('p',{children:'Versioned references for code and art. Your custom skills stay yours.'})]}),h('button',{type:'button',className:'atlas-close','aria-label':'Close knowledge manager',onClick:close,children:'×'})]}),
    j('div',{className:'atlas-dialog-body',children:[
      error&&h('p',{role:'alert',className:'atlas-error',children:error}),notice&&h('p',{role:'status',className:'atlas-notice',children:notice}),
      !status?h('p',{children:'Loading library…'}):j(s.Fragment,{children:[
        j('div',{className:'atlas-library-summary',children:[j('div',{children:[h('strong',{children:statusLabel}),h('p',{children:'Last successful check: '+date(status.config.lastSuccessAt)})]}),j('label',{className:'atlas-auto',children:[h('input',{type:'checkbox',checked:status.config.autoUpdate,disabled:!!pending,onChange:e=>void run('Saving',()=>window.modmixer.atlasLibraryConfigure({autoUpdate:e.target.checked}))}), 'Auto-update daily']})]}),
        status.config.lastError&&h('p',{className:'atlas-warning',children:status.config.lastError+' Current packs are still available.'}),
        j('div',{className:'atlas-actions',children:[h('button',{...buttonProps,onClick:()=>void run('Checking',()=>window.modmixer.atlasLibraryCheck(),value=>value.available.length?value.available.length+' verified update(s) available. Choose Update all to install.':'Your library is up to date.'),children:pending==='Checking'?'Checking…':'Check now'}),h('button',{...buttonProps,className:'atlas-action atlas-primary',onClick:()=>void run('Updating',()=>window.modmixer.atlasLibraryUpdate(),'Verified packs installed. Active work keeps its current references; newly opened chats use the updated library.'),children:pending==='Updating'?'Updating…':'Update all'}),h('button',{...buttonProps,onClick:()=>void run('Opening',()=>window.modmixer.atlasLibraryReveal()),children:'Open library folder'}),h('button',{...buttonProps,onClick:()=>void run('Opening',()=>window.modmixer.atlasLibraryCustom()),children:'My custom skills'}),h('button',{...buttonProps,disabled:!!pending||status.busy,onClick:()=>void run('Rebuilding',()=>window.modmixer.atlasLibraryRebuild(),'Game index rebuild started. Progress is shown by Atlas.'),children:'Rebuild game index'})]}),
        j('details',{className:'atlas-source-settings',children:[h('summary',{children:'Update source'}),h('p',{children:'Use your signed Atlas release folder or HTTPS feed. Downloads must match the publisher key bundled with Atlas. Private notes are never uploaded.'}),j('div',{className:'atlas-source-row',children:[h('input',{'aria-label':'Update source',value:source,onChange:e=>setSource(e.target.value),placeholder:'Folder path or https://…'}),h('button',{...buttonProps,onClick:()=>void run('Saving',()=>window.modmixer.atlasLibraryConfigure({source}), 'Update source saved.'),children:'Save source'}),h('button',{...buttonProps,onClick:()=>void run('Choosing',async()=>{const value=await window.modmixer.atlasLibraryChooseSource();if(value)setSource(value.config.source);return value;}),children:'Choose folder'})]})]}),
        h(AtlasApplicationUpdates,{}),h(AdaptersSection,{}),h('h3',{children:'Installed packs'}),
        status.available.length>0&&h('p',{className:'atlas-notice',children:status.available.length+' verified update(s) available.'}),
        h('div',{className:'atlas-pack-list',children:status.packs.map(pack=>j('article',{className:'atlas-pack',children:[j('div',{className:'atlas-pack-title',children:[h('h4',{children:pack.name}),h('span',{className:'atlas-tag',children:pack.category+' · '+pack.version})]}),h('p',{children:pack.description}),j('div',{className:'atlas-pack-meta',children:[h('span',{children:'Game versions: '+pack.gameVersions.join(', ')}),h('span',{children:'License: '+pack.license})]}),pack.pending&&h('p',{className:'atlas-warning',children:'Version '+pack.pending+' will activate when current work finishes.'}),j('div',{className:'atlas-actions',children:[h('button',{...buttonProps,onClick:()=>void window.modmixer.openExternal(pack.source).catch(e=>setError(e.message)),children:'Source'}),h('button',{...buttonProps,onClick:()=>void run('Opening',()=>window.modmixer.atlasLibraryReveal(pack.id)),children:'Open folder'}),h('button',{...buttonProps,disabled:!!pending||status.busy||!pack.previous,onClick:()=>void run('Reverting',()=>window.modmixer.atlasLibraryRevert(pack.id),'Previous pack restored for new chats.'),children:'Revert'})]})]},pack.id))}),
        status.changes.length>0&&j('details',{className:'atlas-source-settings',children:[h('summary',{children:'Latest changes'}),h('ul',{children:status.changes.map(change=>h('li',{children:change.id+': '+(change.from??'new')+' → '+change.to+' — '+change.notes},change.id))})]}),
        h('h3',{children:'Search references'}),j('form',{className:'atlas-source-row',onSubmit:e=>{e.preventDefault();void run('Searching',async()=>{const found=await window.modmixer.atlasLibrarySearch(query);setResults(found);setNotice(found.length?found.length+' reference file(s) found.':'No matching reference files.');});},children:[h('input',{'aria-label':'Search references',value:query,onChange:e=>setQuery(e.target.value),placeholder:'For example: apparel directions or Harmony'}),h('button',{...buttonProps,type:'submit',children:'Search'})]}),
        h('div',{className:'atlas-search-results',children:results.map(result=>j('article',{className:'atlas-search-result',children:[h('strong',{children:result.id+' / '+result.path}),h('p',{children:result.excerpt}),h('button',{...buttonProps,onClick:()=>void run('Opening',()=>window.modmixer.atlasLibraryOpenReference(result.id,result.path)),children:'Open reference file'})]},result.id+result.path))}),
        h('p',{className:'atlas-footnote',children:'Packs guide the agent; they do not retrain models. Static checks do not prove gameplay or visual correctness. Moving Atlas to another PC may require signing in again and selecting your game folder.'})
      ]})
    ]})
  ]})})]});
}

export {AtlasKnowledgeButton,AtlasApplicationUpdates};
